schema_version: 1

context:
  name: libvalkey-py
  version: "4.0.1"

package:
  name: "${{ name }}"
  version: "${{ version }}"

source:
  url: https://files.pythonhosted.org/packages/source/l/libvalkey/libvalkey-${{ version }}.tar.gz
  sha256: "fe60ef535bc826fc35f4019228a0a46bdce8b41fd6013a7591e822a8a17c3170"

build:
  number: 1
  script:
    content:
      - ${{ PYTHON }} -m pip install --use-pep517 --no-build-isolation .

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}

  host:
    - python
    - setuptools
    - pip
    - if: build_platform != target_platform
      then:
        - cross-python_${{ target_platform }}

  run:
    - python

tests:
  - python:
      imports:
        - libvalkey

about:
  license: MIT
  license_file:
    - LICENSE
  summary: Python extension that wraps protocol parsing code in libvalkey. It primarily speeds up parsing of multi bulk replies.
  description: |
    Python extension that wraps protocol parsing code in libvalkey.
    It primarily speeds up parsing of multi bulk replies.
  homepage: https://github.com/valkey-io/libvalkey-py
  repository: https://github.com/valkey-io/libvalkey-py

extra:
  recipe-maintainers:
    - trim21
